// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAABFXXnj6K-qnreOqw5pyj8cXQ5xw7PEg',
    appId: '1:539222949502:web:34b95fe2bfb0f55de1222f',
    messagingSenderId: '539222949502',
    projectId: 'taskly-8fd96',
    authDomain: 'taskly-8fd96.firebaseapp.com',
    storageBucket: 'taskly-8fd96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfbCuIfWkVgbHB9gLs3XGoGfrJXTkBBcE',
    appId: '1:539222949502:android:3051c810ea29791de1222f',
    messagingSenderId: '539222949502',
    projectId: 'taskly-8fd96',
    storageBucket: 'taskly-8fd96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrWH-LTXZeG5tVDpBaFpGJss0mfXH1eaA',
    appId: '1:539222949502:ios:73cf44b0a8dd0d1be1222f',
    messagingSenderId: '539222949502',
    projectId: 'taskly-8fd96',
    storageBucket: 'taskly-8fd96.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrWH-LTXZeG5tVDpBaFpGJss0mfXH1eaA',
    appId: '1:539222949502:ios:73cf44b0a8dd0d1be1222f',
    messagingSenderId: '539222949502',
    projectId: 'taskly-8fd96',
    storageBucket: 'taskly-8fd96.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAABFXXnj6K-qnreOqw5pyj8cXQ5xw7PEg',
    appId: '1:539222949502:web:f61a6c25434ebb8ae1222f',
    messagingSenderId: '539222949502',
    projectId: 'taskly-8fd96',
    authDomain: 'taskly-8fd96.firebaseapp.com',
    storageBucket: 'taskly-8fd96.firebasestorage.app',
  );
}
